CREATE TABLE BAIRRO(
    ID INT(5) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID))
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE MODELOSCARRO(
    ID    INT(11) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID))
ENGINE=INNODB
CHARACTER SET utf8
collate utf8_generaL_ci;

CREATE TABLE USUARIO(
    ID              INT(11) NOT NULL AUTO_INCREMENT,
    NOME            VARCHAR(30) NOT NULL,    
    MATRICULA       INT NOT NULL,
    BAIRRO_ID       INT NOT NULL,
    DATA_CADASTRO   DATE NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_BAIRRO FOREIGN KEY (BAIRRO_ID) REFERENCES BAIRRO(ID))
ENGINE=INNODB
CHARACTER SET utf8
collate utf8_generaL_ci;


CREATE TABLE CARRO(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    PLACA VARCHAR(7) NOT NULL,
    MODELO_ID INT(11) NOT NULL,
    USUARIO_ID INT(11) NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT FK_MODELO FOREIGN KEY(MODELO_ID) REFERENCES MODELOSCARRO(ID))
ENGINE=INNODB
CHARACTER SET utf8
collate utf8_generaL_ci;


CREATE TABLE USUARIOS(
    CONTA   VARCHAR(30) NOT NULL,
    SENHA   VARCHAR(30) NOT NULL,
    PRIMARY KEY(CONTA))
ENGINE=INNODB
CHARACTER SET utf8
collate utf8_generaL_ci;

CREATE TABLE PERFIS(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    CONTA VARCHAR(30),
    PERFIL VARCHAR(30),
    PRIMARY KEY(ID),
    CONSTRAINT FK_CONTA FOREIGN KEY(CONTA) REFERENCES USUARIOS(CONTA))
ENGINE=INNODB
CHARACTER SET utf8
collate utf8_generaL_ci;



INSERT INTO BAIRRO (NOME) VALUES ("Tijuca");
INSERT INTO BAIRRO (NOME) VALUES ("Ingá");
INSERT INTO BAIRRO (NOME) VALUES ("Icaraí");
INSERT INTO BAIRRO (NOME) VALUES ("Grajaú");
INSERT INTO BAIRRO (NOME) VALUES ("Centro");
INSERT INTO BAIRRO (NOME) VALUES ("Camboinhas");
INSERT INTO BAIRRO (NOME) VALUES ("Vila Isabel");

INSERT INTO MODELOSCARRO (NOME) VALUES ("C10 BMQ");
INSERT INTO MODELOSCARRO (NOME) VALUES ("CITY MASTER");
INSERT INTO MODELOSCARRO (NOME) VALUES ("GIPE");
INSERT INTO MODELOSCARRO (NOME) VALUES ("MACH 5");
INSERT INTO MODELOSCARRO (NOME) VALUES ("FERRADO");

INSERT INTO USUARIO(NOME, MATRICULA, BAIRRO_ID, DATA_CADASTRO) VALUES("Joao", 123456789, 1, CURDATE());
INSERT INTO USUARIO(NOME, MATRICULA, BAIRRO_ID, DATA_CADASTRO) VALUES("Lucas", 12323389, 2, CURDATE());
INSERT INTO USUARIO(NOME, MATRICULA, BAIRRO_ID, DATA_CADASTRO) VALUES("Luan", 12312389, 3, CURDATE());
INSERT INTO USUARIO(NOME, MATRICULA, BAIRRO_ID, DATA_CADASTRO) VALUES("Renato", 133456789, 4, CURDATE());
INSERT INTO USUARIO(NOME, MATRICULA, BAIRRO_ID, DATA_CADASTRO) VALUES("Lohan", 987654321, 5, CURDATE());
INSERT INTO USUARIO(NOME, MATRICULA, BAIRRO_ID, DATA_CADASTRO) VALUES("Thais", 123459876, 6, CURDATE());
INSERT INTO USUARIO(NOME, MATRICULA, BAIRRO_ID, DATA_CADASTRO) VALUES("Julia", 987512345, 7, CURDATE());





INSERT INTO CARRO(PLACA, MODELO_ID, USUARIO_ID) VALUES("ABC5555", 1, 1);
INSERT INTO CARRO(PLACA, MODELO_ID, USUARIO_ID) VALUES("ABC5335", 2, 2);
INSERT INTO CARRO(PLACA, MODELO_ID, USUARIO_ID) VALUES("ABC2755", 3, 3);


INSERT INTO USUARIOS(CONTA, SENHA) VALUES('projsoftware', 'projsoftware');
INSERT INTO PERFIS(CONTA, PERFIL) VALUES('projsoftware', 'admin');

INSERT INTO USUARIOS(CONTA, SENHA) VALUES('outro', 'outro');
INSERT INTO PERFIS(CONTA, PERFIL) VALUES('outro', 'outro');
