CREATE TABLE BAIRRO(
    ID INT(5) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID))
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE MODELOSCARRO(
    ID    INT(11) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID))
ENGINE=INNODB
CHARACTER SET utf8
collate utf8_generaL_ci;

CREATE TABLE USUARIO(
    ID              INT(11) NOT NULL AUTO_INCREMENT,
    NOME            VARCHAR(30) NOT NULL,    
    MATRICULA       INT NOT NULL,
    BAIRRO_ID       INT NOT NULL,
    DATA_CADASTRO   DATE NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_BAIRRO FOREIGN KEY (BAIRRO_ID) REFERENCES BAIRRO(ID))
ENGINE=INNODB
CHARACTER SET utf8
collate utf8_generaL_ci;


CREATE TABLE CARRO(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    PLACA VARCHAR(7) NOT NULL,
    MODELO_ID INT(11) NOT NULL,
    USUARIO_ID INT(11) NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID),
    CONSTRAINT FK_MODELO FOREIGN KEY(MODELO_ID) REFERENCES MODELOSCARRO(ID))
ENGINE=INNODB
CHARACTER SET utf8
collate utf8_generaL_ci;
